export interface StagedTarget {
  uploadUrl: string;
  resourceUrl: string;
  parameters: Array<{ name: string; value: string }>;
}

export type PublishSource =
  | { content: Buffer | string | Blob; filename: string; mimeType?: string }
  | { stagedResourceUrl: string; filename: string };

export interface PublishOptions {
  timeoutMs?: number;
  pollIntervalMs?: number;
  resourceType?: "IMAGE" | "FILE";
}

export interface PublishResult {
  fileId: string;
  publicUrl: string;
}

interface InferredTypes {
  mimeType: string;
  resource: "FILE" | "IMAGE";
  gqlNode: "GenericFile" | "MediaImage";
}

/**
 * Helper to infer file properties and Shopify types from filename extension.
 */
function inferFileProperties(filename: string, mimeTypeOverride?: string): InferredTypes {
  const ext = filename.split(".").pop()?.toLowerCase() || "";
  
  let mimeType = mimeTypeOverride || "application/octet-stream";
  let resource: "FILE" | "IMAGE" = "FILE";
  let gqlNode: "GenericFile" | "MediaImage" = "GenericFile";

  if (!mimeTypeOverride) {
    switch (ext) {
      case "svg":
        mimeType = "image/svg+xml";
        resource = "FILE";
        gqlNode = "GenericFile";
        break;
      case "ttf":
        mimeType = "font/ttf";
        resource = "FILE";
        gqlNode = "GenericFile";
        break;
      case "otf":
        mimeType = "font/otf";
        resource = "FILE";
        gqlNode = "GenericFile";
        break;
      case "woff":
        mimeType = "font/woff";
        resource = "FILE";
        gqlNode = "GenericFile";
        break;
      case "woff2":
        mimeType = "font/woff2";
        resource = "FILE";
        gqlNode = "GenericFile";
        break;
      case "png":
        mimeType = "image/png";
        resource = "IMAGE";
        gqlNode = "MediaImage";
        break;
      case "jpg":
      case "jpeg":
        mimeType = "image/jpeg";
        resource = "IMAGE";
        gqlNode = "MediaImage";
        break;
      case "gif":
        mimeType = "image/gif";
        resource = "IMAGE";
        gqlNode = "MediaImage";
        break;
    }
  } else {
    // If mimeType is explicitly provided, align resource type
    if (mimeType.startsWith("image/") && mimeType !== "image/svg+xml") {
      resource = "IMAGE";
      gqlNode = "MediaImage";
    }
  }

  return { mimeType, resource, gqlNode };
}

/**
 * High-leverage Shopify File Publisher module.
 * Decouples routes from direct GraphQL and S3 POST commands.
 */
export class ShopifyFilePublisher {
  /**
   * Prepares a staged upload target on Shopify's managed storage.
   */
  async stage(
    admin: any,
    filename: string,
    fileSize: number,
    mimeType?: string
  ): Promise<StagedTarget> {
    const { mimeType: inferredMime, resource } = inferFileProperties(filename, mimeType);

    const response = await admin.graphql(
      `#graphql
      mutation stagedUploadsCreate($input: [StagedUploadInput!]!) {
        stagedUploadsCreate(input: $input) {
          stagedTargets {
            url
            resourceUrl
            parameters {
              name
              value
            }
          }
          userErrors {
            field
            message
          }
        }
      }`,
      {
        variables: {
          input: [
            {
              filename,
              httpMethod: "POST",
              mimeType: inferredMime,
              resource,
              fileSize: String(fileSize),
            },
          ],
        },
      }
    );

    const json = await response.json();
    const userErrors = json.data?.stagedUploadsCreate?.userErrors;
    if (userErrors && userErrors.length > 0) {
      throw new Error(`Shopify upload staging failed: ${userErrors[0].message}`);
    }

    const target = json.data?.stagedUploadsCreate?.stagedTargets?.[0];
    if (!target) {
      throw new Error("Staging target was not generated by Shopify.");
    }

    return {
      uploadUrl: target.url,
      resourceUrl: target.resourceUrl,
      parameters: target.parameters,
    };
  }

  /**
   * Finalizes file publishing. Stages/uploads if direct data is supplied,
   * registers the file in the Files library, and polls for the public CDN URL.
   */
  async publish(
    admin: any,
    source: PublishSource,
    options?: PublishOptions
  ): Promise<PublishResult> {
    const timeoutMs = options?.timeoutMs ?? 8000;
    const pollIntervalMs = options?.pollIntervalMs ?? 800;

    let resourceUrl = "";
    let filename = source.filename;
    let mimeType: string | undefined;

    // 1. Stage and upload content to bucket if server-side direct publish
    if ("content" in source) {
      const content = source.content;
      mimeType = source.mimeType;

      let fileBlob: Blob;
      if (content instanceof Blob) {
        fileBlob = content;
      } else if (typeof content === "string") {
        fileBlob = new Blob([content], { type: mimeType });
      } else {
        fileBlob = new Blob([content as any], { type: mimeType });
      }

      const fileSize = fileBlob.size;
      const target = await this.stage(admin, filename, fileSize, mimeType);

      // Build multipart/form-data payload and POST upload to pre-signed URL
      const uploadForm = new FormData();
      target.parameters.forEach((param) => {
        uploadForm.append(param.name, param.value);
      });
      uploadForm.append("file", fileBlob, filename);

      const uploadResponse = await fetch(target.uploadUrl, {
        method: "POST",
        body: uploadForm,
      });

      if (!uploadResponse.ok) {
        const errorText = await uploadResponse.text();
        throw new Error(`S3 bucket file upload failed: ${errorText} (${uploadResponse.status})`);
      }

      resourceUrl = target.resourceUrl;
    } else {
      // Direct client-side staging URL registration
      resourceUrl = source.stagedResourceUrl;
    }

    // 2. Resolve content mappings (GenericFile vs MediaImage)
    const { gqlNode, resource: resolvedResource } = inferFileProperties(
      filename,
      mimeType
    );
    const finalResourceType = options?.resourceType ?? resolvedResource;
    const finalGqlNode = options?.resourceType
      ? (options.resourceType === "IMAGE" ? "MediaImage" : "GenericFile")
      : gqlNode;

    // 3. Register the file in the merchant's Files library
    const fileCreateResponse = await admin.graphql(
      `#graphql
      mutation fileCreate($files: [FileCreateInput!]!) {
        fileCreate(files: $files) {
          files {
            id
            fileStatus
          }
          userErrors {
            field
            message
          }
        }
      }`,
      {
        variables: {
          files: [
            {
              originalSource: resourceUrl,
              contentType: finalResourceType,
              filename,
            },
          ],
        },
      }
    );

    const fileCreateJson = await fileCreateResponse.json();
    const createErrors = fileCreateJson.data?.fileCreate?.userErrors;
    if (createErrors && createErrors.length > 0) {
      throw new Error(`Shopify File registry failed: ${createErrors[0].message}`);
    }

    const createdFile = fileCreateJson.data?.fileCreate?.files?.[0];
    if (!createdFile) {
      throw new Error("Shopify File registry returned empty records.");
    }

    const fileId = createdFile.id;
    let publicUrl = "";

    // 4. Poll node to retrieve the processed CDN URL
    let pollCount = 0;
    const maxPolls = Math.ceil(timeoutMs / pollIntervalMs);

    while (pollCount < maxPolls && !publicUrl) {
      await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));

      let checkResponse;
      if (finalGqlNode === "MediaImage") {
        checkResponse = await admin.graphql(
          `#graphql
          query getMediaImage($id: ID!) {
            node(id: $id) {
              ... on MediaImage {
                image {
                  url
                }
              }
            }
          }`,
          { variables: { id: fileId } }
        );
        const checkJson = await checkResponse.json();
        publicUrl = checkJson.data?.node?.image?.url || "";
      } else {
        checkResponse = await admin.graphql(
          `#graphql
          query getGenericFile($id: ID!) {
            node(id: $id) {
              ... on GenericFile {
                url
              }
            }
          }`,
          { variables: { id: fileId } }
        );
        const checkJson = await checkResponse.json();
        publicUrl = checkJson.data?.node?.url || "";
      }

      pollCount++;
    }

    if (!publicUrl) {
      console.warn("Shopify CDN URL did not resolve in time. Falling back to resourceUrl.");
    }

    return {
      fileId,
      publicUrl: publicUrl || resourceUrl,
    };
  }
}
