api_version = "2025-10"
uid = "6261e450-34ac-b1f1-78c8-c838701d7988bf3c1976"

[[extensions]]
type = "ui_extension"
name = "Product Personalizer Checkout"
handle = "product-personalizer-checkout"

[[extensions.targeting]]
target = "purchase.checkout.cart-line-item.render-after"
module = "./src/Checkout.ts"

[[extensions.metafields]]
namespace = "app"
key = "customization_config"

[extensions.capabilities]
api_access = true
