api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-transform-function"
type = "function"
uid = "97dbeb25-f261-7938-2ec0-85085cb449f1efcd8913"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
